[[assignments]]
name = "git"
description = "something"
prefix = "git-"

  [[assignments.tasks]]
  name = "test"
  queue = "test"
  image = "mocha"
  data = "/github/somewhere"

  [[assignments.tasks]]
  name = "lint"
  queue = "lint"
  image = "eslint"
  data = "/github/somewhere_else"

[[assignments]]
name = "wc"
description = "something"
prefix = "wc-"

  [[assignments.tasks]]
  name = "test"
  queue = "test"
  image = "steptw/test"
  data = "/github/somewhere"

  [[assignments.tasks]]
  name = "lint"
  queue = "lint"
  image = "steptw/eslint"
  data = "/github/somewhere_else"