[assignments]
  [assignments.gol]
    description="this is to make a game of life"
    strategy="prefix"
    match_value="gol"

    [[assignments.gol.tasks]]
      job_name="test"
      queue_name="test"
      image_name="mocha"
      data_path="/tmp/tests"
    
    [[assignments.gol.tasks]]
      job_name="lint"
      queue_name="lint"
      image_name="eslint"
      data_path="/tmp/lint"